### ISSUE TITLE
Allow options to be passed to plugins from the config

### ISSUE THREAD

**Issue by the1900** [phenomic/phenomic#1139]
when it comes to using gitlab pages. [It can only serve public folder to use gitlab page](https://docs.gitlab.com/ee/user/project/pages/getting_started_part_four.html#the-public-directory). So I need to change the destination which is `dist` to `public` but how?

Oh I'm using latest alpha version.

Here is a current `gitlab-ci.yml` and it can download artifact but there is nothing on the gitlabpage.

``` yml
image: node:6

cache:
  paths:
  - node_modules/

build:
  script:
    - npm config set loglevel warn
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist
  only:
  - master
```
